name: Embed YandexTranslate.yaml into README files

on:
  push:
    branches: [ main ]
    paths:
      - 'YandexTranslate.yaml'
      - 'README.md'
      - 'README.ru.md'
      - '.github/workflows/embed-code.yml'
  workflow_dispatch:

jobs:
  embed:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Debug - List files
        run: |
          echo "=== Listing repository files ==="
          ls -la
          echo ""
          echo "=== Content of YandexTranslate.yaml ==="
          cat YandexTranslate.yaml
          echo ""
          echo "=== Checking README files ==="
          if [ -f "README.md" ]; then
            echo "README.md exists"
            grep -n "BEGIN:YandexTranslate" README.md || echo "Marker BEGIN not found in README.md"
            grep -n "END:YandexTranslate" README.md || echo "Marker END not found in README.md"
          else
            echo "README.md NOT found"
          fi
          if [ -f "README.ru.md" ]; then
            echo "README.ru.md exists"
            grep -n "BEGIN:YandexTranslate" README.ru.md || echo "Marker BEGIN not found in README.ru.md"
            grep -n "END:YandexTranslate" README.ru.md || echo "Marker END not found in README.ru.md"
          else
            echo "README.ru.md NOT found"
          fi
        
      - name: Embed code into README files
        shell: bash
        run: |
          BACKTICKS='```
          
          echo "${BACKTICKS}yaml" > temp_code.txt
          cat YandexTranslate.yaml >> temp_code.txt
          echo "${BACKTICKS}" >> temp_code.txt
          
          echo "=== Generated code block ==="
          cat temp_code.txt
          echo ""
          
          update_readme() {
            local file=$1
            
            if [ ! -f "$file" ]; then
              echo "ERROR: File $file not found"
              return 1
            fi
            
            if ! grep -q "<!-- BEGIN:YandexTranslate -->" "$file"; then
              echo "ERROR: BEGIN marker not found in $file"
              return 1
            fi
            
            if ! grep -q "<!-- END:YandexTranslate -->" "$file"; then
              echo "ERROR: END marker not found in $file"
              return 1
            fi
            
            sed -n '1,/<!-- BEGIN:YandexTranslate -->/p' "$file" > "${file}.new"
            cat temp_code.txt >> "${file}.new"
            sed -n '/<!-- END:YandexTranslate -->/,$p' "$file" >> "${file}.new"
            
            mv "${file}.new" "$file"
            echo "✓ Successfully updated $file"
          }
          
          update_readme "README.md"
          update_readme "README.ru.md"
          
          rm -f temp_code.txt
          
      - name: Show changes
        run: |
          echo "=== Git diff ==="
          git diff
          
      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          if git diff --quiet; then
            echo "No changes to commit"
          else
            git add README.md README.ru.md
            git commit -m "docs: auto-update embedded YandexTranslate.yaml"
            git push
            echo "✓ Changes committed and pushed"
          fi
